import { sqliteTable, text, real, integer } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { households } from '../household';
import { categories } from '../category';

/**
 * MonthlyAnalyticsRollup - Pre-aggregated monthly financial data.
 * Used for fast reporting and chart queries.
 * Automatically generated by a monthly job.
 */
export const monthlyAnalyticsRollups = sqliteTable('monthly_analytics_rollups', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  householdId: text('household_id')
    .notNull()
    .references(() => households.id, { onDelete: 'cascade' }),
  
  // Month in YYYY-MM format
  month: text('month').notNull(),
  
  // Optional category breakdown (null = totals for the month)
  categoryId: text('category_id')
    .references(() => categories.id, { onDelete: 'cascade' }),
  
  // Aggregated values
  totalIncome: real('total_income').notNull().default(0),
  totalExpense: real('total_expense').notNull().default(0),
  totalTransfers: real('total_transfers').notNull().default(0),
  transactionCount: integer('transaction_count').notNull().default(0),
  
  // Additional metrics
  uniqueDaysWithTransactions: integer('unique_days_with_transactions').default(0),
  largestTransaction: real('largest_transaction'),
  averageTransactionSize: real('average_transaction_size'),
  
  // Timestamps
  createdAt: integer('created_at', { mode: 'timestamp' })
    .notNull()
    .default(sql`(unixepoch())`),
  updatedAt: integer('updated_at', { mode: 'timestamp' })
    .notNull()
    .default(sql`(unixepoch())`),
});

export type MonthlyAnalyticsRollup = typeof monthlyAnalyticsRollups.$inferSelect;
export type NewMonthlyAnalyticsRollup = typeof monthlyAnalyticsRollups.$inferInsert;
