import { sqliteTable, text, real, integer } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { households } from '../household';

/**
 * NetWorthSnapshot - Daily snapshots of net worth for fast historical charts.
 * Automatically generated by a daily job.
 */
export const netWorthSnapshots = sqliteTable('net_worth_snapshots', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  householdId: text('household_id')
    .notNull()
    .references(() => households.id, { onDelete: 'cascade' }),
  
  // Snapshot date (normalized to midnight UTC)
  date: integer('date', { mode: 'timestamp' }).notNull(),
  
  // Totals
  totalAssets: real('total_assets').notNull(),
  totalLiabilities: real('total_liabilities').notNull(),
  netWorth: real('net_worth').notNull(),
  
  // Asset breakdown by type (JSON)
  // Format: { "bank_account": 50000, "stock": 100000, "crypto": 5000, ... }
  breakdown: text('breakdown', { mode: 'json' }).notNull(),
  
  // Primary currency used for calculations
  primaryCurrency: text('primary_currency').notNull().default('USD'),
  
  // Timestamps
  createdAt: integer('created_at', { mode: 'timestamp' })
    .notNull()
    .default(sql`(unixepoch())`),
});

export type NetWorthSnapshot = typeof netWorthSnapshots.$inferSelect;
export type NewNetWorthSnapshot = typeof netWorthSnapshots.$inferInsert;

/**
 * Asset breakdown type for the JSON field.
 */
export type AssetBreakdown = {
  bank_account?: number;
  stock?: number;
  crypto?: number;
  real_estate?: number;
  superannuation?: number;
  personal_asset?: number;
  business_asset?: number;
  [key: string]: number | undefined;
};
